### ISSUE TITLE
Compatible with M2.4.*

### ISSUE THREAD

**Issue by leonhelmus** [EmicoEcommerce/Magento2RobinHq#15]
This module is not compatible with M2.4.*.

Here are dependencies i'm missing:
"magento/module-customer": "101.*|102.*", (M2.4 uses 103.*)
"magento/module-catalog": "102.*|103.*", (M2.4 uses 104.*)
"magento/module-sales": "101.*|102.*",(M2.4 uses 103.*)
"magento/framework": "101.*|102.*", (M2.4 uses 103*)

**Comment by leonhelmus** [comment]
Created a PR for the change. I just don't know why it doesn't pass PR checker: https://github.com/EmicoEcommerce/Magento2RobinHq/pull/16

**Comment by leonhelmus** [comment]
@bramstroker @stijnbernards Has there been any progress with M2.4.0?

**Comment by leonhelmus** [comment]
@bramstroker  @stijnbernards  As of this moment i did not hear any issues concerning RobinHq module. So i think you can add the stable tag :+1:

**Comment by bramstroker** [comment]
Thanks @leonhelmus.
We were also using the beta for one of our customers and also did not hear any issues. So I tagged the stable.
