### ISSUE TITLE
Installation on Composer 2 will (most likely) fail.

### ISSUE THREAD

**Issue by reense** [EmicoEcommerce/Magento2RobinHq#31]
While running `composer install --no-dev -o` with Composer 1.x I'm getting the following message:
```
Deprecation Notice: Class Emico\RobinHqLib\Client\InvalidApiResponseException located in ./vendor/emico/robinhq-lib/src/Client/Exception/InvalidApiResponseException.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```
Most of the time, this happens when classes are not named properly (e.g the file name is capitalized differently from the class name). However, in this case I'm unable to see what's wrong.

**Comment by bramstroker** [comment]
This was already fixed long time ago.
https://github.com/EmicoEcommerce/RobinHqLib/commit/dc88c5e174e9708df7bd56d41e3b72a2bc000911
