### ISSUE TITLE
Magento - ROBINHQ - SBA (telephone connection)

### ISSUE THREAD

**Issue by renskewolters** [EmicoEcommerce/Magento2RobinHq#37]
Within the module there's the possibility for matching phonenumbers based on the last 9 digits, however the way this is implemented currently won't work.

On line 114 of the file SearchDataProvider.php the code expects the numerical string to contain only 9 digits, however the string will always remain the same (in this case +31612345678), this causes the module to never actually check for results found for the last 9 digits.

Contact CM.COM 

Wij hebben nog wat extra onderzoek gedaan en zien dat er momenteel in de integratie met Magento bij het endpoint voor de klantgegevens (https://www.open32.nl/robinhq/api/customer?email= ). Nu is [de extensie/module](https://github.com/EmicoEcommerce/Magento2RobinHq/) die hiervoor gebruikt wordt ontwikkeld door Emico in opdracht van een klant van ons, hierdoor kunnen wij hier beperkt support voor bieden.

Hierin speelt momenteel het probleem dat de manier waarop de oplossing voor het negeren van verschillen in notatie verkeerd is ingebouwd. Ons aanraden zou zijn om op de [GitHub pagina](https://github.com/EmicoEcommerce/Magento2RobinHq/) een nieuw ticket/issue aan te maken.

Gezien dit issue nogal lastig uit te leggen zal zijn, heb ik wel een korte tekst geschreven ter begeleiding:

**Comment by cjfloermans** [comment]
Hallo Renske, dit is aangepast in versie v2.1.0 van de module
