### ISSUE TITLE
Magento version 2.4.4-p2 - Robin HQ module 

### ISSUE THREAD

**Issue by DominiqueBerende** [EmicoEcommerce/Magento2RobinHq#47]
Hi,

On 23-11, we've updated our Magento version to 2.4.4-p2 (php 8.1). Since this update, we've experienced some issues with RobinHQ. 
Before the update, we were able to see the orders per customer in detail in Robin, such as ordered products and payment method. Now, when we click on the orders per customer, it says 'undefined'. It seems that the Robin module doesn't work well with this new version of Magento.

It gives the following error:
"message": "Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/domains/viavai-viavaishoes.com/application/releases/500/vendor/emico/magento-2-robinhq/src/Model/Config.php on line 124"

![Example 1 - orders](https://user-images.githubusercontent.com/119491127/204760836-318380ca-fa10-4d1d-8639-9285371515bf.JPG)
![Example 2 - orders undefined](https://user-images.githubusercontent.com/119491127/204760842-43e6bd48-27fc-4908-89af-68e3ce9ae2aa.JPG)

**Comment by DominiqueBerende** [comment]
Hi,

Can I please get any response on this?

Thanks!

**Comment by bramstroker** [comment]
@DominiqueBerende Thanks for raising this issue. We have planned to have a look into this coming thursday.
