### ISSUE TITLE
Error while checking if topic is synchronous during setup:upgrade

### ISSUE THREAD

**Issue by Shiriaev** [EmicoEcommerce/Magento2RobinHq#48]
Hello! 

During bin/magento setup:upgrade command (Schema post-updates section) I faced with the issue:

Module 'Magento_Amqp':                                                      
Error while checking if topic is synchronous

If I revert the changes and deploy without module, all working fine.

RabbitHQ enabled, I can connect to it via rabbithqadmin and see async.operations.all queue.

Magento 2.4.4-p1, RobinHQ module the latest at this moment.

Any ideas how to fix?

Thanks!

**Comment by bramstroker** [comment]
@Shiriaev Thanks for raising this issue. We have planned to have a look into this coming thursday.

**Comment by jlsdohmen** [comment]
@Shiriaev We were not able to reproduce this issue on a clean install of Magento 2.4.4-p1.  Please check the following [comment](https://github.com/EmicoEcommerce/Magento2RobinHq/issues/18#issuecomment-805647063) to see if it fixes the problem in your case as well.

If the problem persists, please debug to investigate where the original exception is thrown causing this error message.
