### ISSUE TITLE
Deeplink to order within Admin panel

### ISSUE THREAD

**Issue by Raven-VS** [EmicoEcommerce/Magento2RobinHq#6]
Within the order detail endpoint the JSON-field "url" is used to append a URL to the button at the bottom, which links to the order within the admin panel. 

This URL is currently returned as 'null'.

**Comment by bramstroker** [comment]
@Raven-VS This has been resolved in release 1.0.4.
We have tested in 4 different Magento installations.
You have to be logged in into the Magento admin to make the deeplink work, otherwise you will be redirected to the dashboard.
