### ISSUE TITLE
Update to v4.1.2 causes TypeError on LoggedInCustomer::getEmail()

### ISSUE THREAD

**Issue by femkepetter** [EmicoEcommerce/Magento2RobinHq#61]
The update to version 4.1.2 results in the following error: 

`CRITICAL: TypeError: Emico\\RobinHq\\ViewModel\\LoggedInCustomer::getEmail(): Return value must be of type string, null returned in /data/web/releases/20240402095542/vendor/emico/magento-2-robinhq/src/ViewModel/LoggedInCustomer.php:50`

Downgrading to 4.0.0 eliminates the issue.

**Comment by bramstroker** [comment]
@femkepetter thanks for reporting. Should be fixed in v4.1.3
